name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: '18' }

      - name: SSH & deploy
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_KEY:  ${{ secrets.EC2_KEY }}
          EC2_USER: ec2-user
        run: |
          echo "$EC2_KEY" > key.pem && chmod 400 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
            set -e
            mkdir -p ~/myapp && cd ~/myapp
            if [ -d .git ]; then
              git fetch origin main && git reset --hard origin/main
            else
              git clone https://github.com/<your‑user>/<repo>.git .
            fi
            npm ci                     # clean install
            pm2 startOrReload ecosystem.config.js
            pm2 save
          EOF